apiVersion: v1
kind: Secret
metadata:
  name: mechanic-secret
  namespace: default

type: Opaque

stringData:
  dbPassword: "YourStrong!Passw0rd"
  connectionString: "Server=mechanic-db-service;Database=MechanicDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"