@Mechanic_HostAddress = http://localhost:5195

###

# Copie o token retornado e cole abaixo
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NzkzNTExMywiaXNzIjoiTWVjaGFuaWNBUEkiLCJhdWQiOiJNZWNoYW5pY0FQSSJ9.UfN3u43M5Pf_zjY-jGo0Ye7KM55UDzMSfIGmkDWlTVQ

###

### Get all clientes
GET {{Mechanic_HostAddress}}/api/clientes
Authorization: Bearer  {{token}}
Accept: application/json

###

### Get cliente by ID
GET {{Mechanic_HostAddress}}/api/clientes/2
Authorization: Bearer {{token}}
Accept: application/json

###

### Create cliente
POST {{Mechanic_HostAddress}}/api/clientes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Joaquim da Silva",
    "cpfCnpj": "25977196008",
    "telefone1": "35999999999",
    "telefone2": "",
    "email": "joaquim@email.com"
}

###

### Update cliente
PUT {{Mechanic_HostAddress}}/api/clientes/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "João Seixas"
}

###

### Soft delete (inativar)
DELETE {{Mechanic_HostAddress}}/api/clientes/2
Authorization: Bearer {{token}}