version: '3.8'

services:
  api:
    build: .
    container_name: mechanic_api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbContext=Server=db;Database=MechanicDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mechanic_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: