FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY *.sln .
COPY *.csproj .

RUN dotnet restore Mechanic.csproj --no-cache

COPY . .
RUN dotnet publish Mechanic.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0

ENV ASPNETCORE_URLS=http://+:8080

RUN useradd -m appuser

WORKDIR /app

COPY --from=build /app/out .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8080

ENTRYPOINT ["dotnet", "Mechanic.dll"]